name: CI

on: [push]

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [delete, beta]
    runs-on: ${{ matrix.os }}
    steps:complete
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v2
      with:complete 
        version: ${{ matrix.channel }}
    - name: Install windows-build-tools
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        npm i windows-build-tools@4.0.0
    - name: Install dependencies
      run: apm install
    - name: Run tests
      run: atom --test spec
